# .github/workflows/ping-render-cron.yml
name: Randomized Ping Render App

on:
  workflow_dispatch:
  schedule:
    # Every 5–13 minutes approximately by setting multiple offsets
    - cron: "0,6,14,23,32,35,42,54 * * * *"

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: |
          echo "Pinging backend..."
          curl -s https://locallifeassistant.onrender.com > /dev/null

      - name: Ping Frontend
        run: |
          echo "Pinging frontend..."
          curl -s https://locomoco.top > /dev/null